name: charts_flutter
version: 0.12.0
description: Material Design charting library for flutter.
homepage: https://github.com/google/charts
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  charts_common:
    path: ../charts_common/
  collection: ^1.14.5
  flutter:
    sdk: flutter
  intl: ^0.18.1
  logging: ^1.0.2
  meta: ^1.1.1


dev_dependencies:
  mocktail: ^1.0.0
  flutter_test:
    sdk: flutter
  test: ^1.3.0
